# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       openobex

# >> macros
# << macros

Summary:    Library for using OBEX
Version:    1.5
Release:    1
Group:      System/Libraries
License:    GPLv2+
URL:        http://openobex.org
Source0:    http://www.kernel.org/pub/linux/bluetooth/%{name}-%{version}.tar.gz
Source100:  openobex.yaml
Patch0:     fix-the-cmd-code-when-delivering.patch
Patch1:     001_null_check.patch
Patch2:     ensure-socket-buffer-size.patch
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(libusb)
BuildRequires:  autoconf
BuildRequires:  sed
BuildRequires:  automake
BuildRequires:  autoconf
BuildRequires:  libtool

%description
Open OBEX shared c-library

%package devel
Summary:    Files for development of applications which will use OBEX
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   bluez-libs-devel

%description devel
Open OBEX shared c-library

%prep
%setup -q -n %{name}-%{version}/openobex

# fix-the-cmd-code-when-delivering.patch
%patch0 -p1
# 001_null_check.patch
%patch1 -p1
# ensure-socket-buffer-size.patch
%patch2 -p1
# >> setup
# << setup

%build
# >> build pre
./bootstrap
# << build pre

%configure --disable-static \
    --enable-usb \
    --disable-bluetooth \
    --disable-apps

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
# >> files
%doc AUTHORS COPYING COPYING.LIB ChangeLog README
%{_libdir}/libopenobex*.so.*
# << files

%files devel
%defattr(-,root,root,-)
# >> files devel
%{_libdir}/libopenobex*.so
%dir %{_includedir}/openobex
%{_includedir}/openobex/*.h
%{_libdir}/pkgconfig/openobex.pc
# << files devel
